### ISSUE TITLE
点击田字格的Demo 的时候报了个错

### ISSUE THREAD

**Issue by liyuzhao** [Shimingli/WritingPen#7]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2829)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:191)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1617)

**Comment by Shimingli** [comment]
解决了么？
